#!/usr/bin/env python3
# Copyright (c) 2019-2020 The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Test that we reject low difficulty headers to prevent our block tree from filling up with useless bloat.

Currently uses regtest and data/blockheader_testnet.hex (Zorkcoin 88-byte headers: 64-bit nTime,
64-bit nNonce). The file is generated by generate_blockheader_testnet_data.py on regtest so that
301 blocks can be created quickly. A regtest checkpoint at height 300 in chainparams.cpp ensures
fork headers are rejected with bad-fork-prior-to-checkpoint; other regtest tests are unaffected
because GetLastCheckpoint() only considers checkpoints that exist in the current chain.

TODO: Convert back to testnet for consistency with the original design. Instructions:
  1. Mine (or sync) Zorkcoin testnet past block 300 so you have a chain 0..300.
  2. Run the generator against testnet to create a new blockheader_testnet.hex:
     - In generate_blockheader_testnet_data.py: set self.chain = 'testnet', use TESTNET_NBITS
       (0x1f0007f8) and testnet genesis time for fork blocks; increase node.rpc_timeout (e.g. 600)
       before generatetoaddress(301) since testnet mining is slow.
     - Run: python3 generate_blockheader_testnet_data.py --configfile=../config.ini
     - The script will write the data file and print the checkpoint hash (block 300) and fork tip hash.
  3. In src/chainparams.cpp:
     - CTestNetParams checkpointData: add { 300, uint256S("0x<checkpoint_hash>") } (use hash from step 2).
     - CRegTestParams checkpointData: remove the { 300, ... } entry (revert to genesis-only).
  4. In this file (p2p_dos_header_tree.py):
     - Set self.chain = 'testnet'.
     - Update the two expected 'hash' values (checkpoint tip and fork tip) to those printed in step 2.
  5. Rebuild and run: test/functional/test_runner.py -j 1 p2p_dos_header_tree.py
"""

from test_framework.messages import (
    CBlockHeader,
    FromHex,
)
from test_framework.p2p import (
    P2PInterface,
    msg_headers,
)
from test_framework.test_framework import BitcoinTestFramework, SkipTest

import os


class RejectLowDifficultyHeadersTest(BitcoinTestFramework):
    def set_test_params(self):
        self.setup_clean_chain = True
        self.chain = 'regtest'  # TODO: switch back to 'testnet' after regenerating data from testnet; see module docstring
        self.num_nodes = 2

    def add_options(self, parser):
        parser.add_argument(
            '--datafile',
            default='data/blockheader_testnet.hex',
            help='Test data file (default: %(default)s)',
        )

    def run_test(self):
        self.log.info("Read headers data")
        self.headers_file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), self.options.datafile)
        with open(self.headers_file_path, encoding='utf-8') as headers_data:
            h_lines = [l.strip() for l in headers_data.readlines()]

        # The headers data is taken from testnet for early blocks from genesis until the first checkpoint. There are
        # two headers with valid POW at height 1 and 2, forking off from genesis. They are indicated by the FORK_PREFIX.
        FORK_PREFIX = 'fork:'
        self.headers = [l for l in h_lines if not l.startswith(FORK_PREFIX)]
        self.headers_fork = [l[len(FORK_PREFIX):] for l in h_lines if l.startswith(FORK_PREFIX)]

        self.headers = [FromHex(CBlockHeader(), h) for h in self.headers]
        self.headers_fork = [FromHex(CBlockHeader(), h) for h in self.headers_fork]

        self.log.info("Feed all non-fork headers, including and up to the first checkpoint")
        peer_checkpoint = self.nodes[0].add_p2p_connection(P2PInterface())
        peer_checkpoint.send_and_ping(msg_headers(self.headers))
        assert {
            'height': 300,
            'hash': '21ab8f9555ec58552b2491c20babc7872bf9e991d387630a7cf508c0c85b3ebc',
            'branchlen': 300,
            'status': 'headers-only',
        } in self.nodes[0].getchaintips()

        self.log.info("Feed all fork headers (fails due to checkpoint)")
        with self.nodes[0].assert_debug_log(['bad-fork-prior-to-checkpoint']):
            peer_checkpoint.send_message(msg_headers(self.headers_fork))
            peer_checkpoint.wait_for_disconnect()

        self.log.info("Feed all fork headers (succeeds without checkpoint)")
        # On node 0 it succeeds because checkpoints are disabled
        self.restart_node(0, extra_args=['-nocheckpoints'])
        peer_no_checkpoint = self.nodes[0].add_p2p_connection(P2PInterface())
        peer_no_checkpoint.send_and_ping(msg_headers(self.headers_fork))
        assert {
            "height": 2,
            "hash": "f301dd9a99c3e1148a42da6010ff34f64e46f27177306c868baf76ebea2afe67",
            "branchlen": 2,
            "status": "headers-only",
        } in self.nodes[0].getchaintips()

        # On node 1 it succeeds because no checkpoint has been reached yet by a chain tip
        peer_before_checkpoint = self.nodes[1].add_p2p_connection(P2PInterface())
        peer_before_checkpoint.send_and_ping(msg_headers(self.headers_fork))
        assert {
            "height": 2,
            "hash": "f301dd9a99c3e1148a42da6010ff34f64e46f27177306c868baf76ebea2afe67",
            "branchlen": 2,
            "status": "headers-only",
        } in self.nodes[1].getchaintips()


if __name__ == '__main__':
    RejectLowDifficultyHeadersTest().main()
